[package]
name = "sample-app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3.0.0-alpha.3"
actix-rt = "1.1.1"
listenfd = "0.3"
dotenv = "0.11"
env_logger = "0.7.1"
serde = "1.0"
serde_json = "1.0"